// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250305103703_AddKategoriTable")]
    partial class AddKategoriTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("dotnet_store.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KategoriAdi = "Telefon",
                            Url = "telefon"
                        },
                        new
                        {
                            Id = 2,
                            KategoriAdi = "Elektronik",
                            Url = "elektronik"
                        },
                        new
                        {
                            Id = 3,
                            KategoriAdi = "Beyaz Eşya",
                            Url = "beyaz-esya"
                        },
                        new
                        {
                            Id = 4,
                            KategoriAdi = "Giyim",
                            Url = "giyim"
                        },
                        new
                        {
                            Id = 5,
                            KategoriAdi = "Kozmetik",
                            Url = "kozmetik"
                        },
                        new
                        {
                            Id = 6,
                            KategoriAdi = "Kategori 1",
                            Url = "kategori-1"
                        },
                        new
                        {
                            Id = 7,
                            KategoriAdi = "Kategori 2",
                            Url = "kategori-2"
                        },
                        new
                        {
                            Id = 8,
                            KategoriAdi = "Kategori 3",
                            Url = "kategori-3"
                        },
                        new
                        {
                            Id = 9,
                            KategoriAdi = "Kategori 4",
                            Url = "kategori-4"
                        },
                        new
                        {
                            Id = 10,
                            KategoriAdi = "Kategori 5",
                            Url = "kategori-5"
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anasayfa")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Fiyat")
                        .HasColumnType("REAL");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resim")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis quam accusamus neque tempore, consequatur dolor, nihil impedit recusandae ad adipisci eveniet libero ipsum quidem optio laboriosam, ea ipsa ducimus iusto?",
                            Aktif = false,
                            Anasayfa = true,
                            Fiyat = 10000.0,
                            KategoriId = 1,
                            Resim = "1.jpeg",
                            UrunAdi = "Apple Watch 7"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis quam accusamus neque tempore, consequatur dolor, nihil impedit recusandae ad adipisci eveniet libero ipsum quidem optio laboriosam, ea ipsa ducimus iusto?",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 20000.0,
                            KategoriId = 1,
                            Resim = "2.jpeg",
                            UrunAdi = "Apple Watch 8"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis quam accusamus neque tempore, consequatur dolor, nihil impedit recusandae ad adipisci eveniet libero ipsum quidem optio laboriosam, ea ipsa ducimus iusto?",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 30000.0,
                            KategoriId = 2,
                            Resim = "3.jpeg",
                            UrunAdi = "Apple Watch 9"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis quam accusamus neque tempore, consequatur dolor, nihil impedit recusandae ad adipisci eveniet libero ipsum quidem optio laboriosam, ea ipsa ducimus iusto?",
                            Aktif = false,
                            Anasayfa = false,
                            Fiyat = 40000.0,
                            KategoriId = 2,
                            Resim = "4.jpeg",
                            UrunAdi = "Apple Watch 10"
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis quam accusamus neque tempore, consequatur dolor, nihil impedit recusandae ad adipisci eveniet libero ipsum quidem optio laboriosam, ea ipsa ducimus iusto?",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 50000.0,
                            KategoriId = 2,
                            Resim = "5.jpeg",
                            UrunAdi = "Apple Watch 11"
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis quam accusamus neque tempore, consequatur dolor, nihil impedit recusandae ad adipisci eveniet libero ipsum quidem optio laboriosam, ea ipsa ducimus iusto?",
                            Aktif = false,
                            Anasayfa = false,
                            Fiyat = 60000.0,
                            KategoriId = 3,
                            Resim = "6.jpeg",
                            UrunAdi = "Apple Watch 12"
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis quam accusamus neque tempore, consequatur dolor, nihil impedit recusandae ad adipisci eveniet libero ipsum quidem optio laboriosam, ea ipsa ducimus iusto?",
                            Aktif = false,
                            Anasayfa = false,
                            Fiyat = 70000.0,
                            KategoriId = 3,
                            Resim = "7.jpeg",
                            UrunAdi = "Apple Watch 14"
                        },
                        new
                        {
                            Id = 8,
                            Aciklama = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis quam accusamus neque tempore, consequatur dolor, nihil impedit recusandae ad adipisci eveniet libero ipsum quidem optio laboriosam, ea ipsa ducimus iusto?",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 80000.0,
                            KategoriId = 4,
                            Resim = "8.jpeg",
                            UrunAdi = "Apple Watch 15"
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Urun", b =>
                {
                    b.HasOne("dotnet_store.Models.Kategori", "Kategori")
                        .WithMany("Uruns")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("dotnet_store.Models.Kategori", b =>
                {
                    b.Navigation("Uruns");
                });
#pragma warning restore 612, 618
        }
    }
}
